version: '3.9'

services:
  php:
    container_name: ricardo-php
    restart: on-failure
    image: docker.io/library/ricardo-technical-test:develop
    build: .
    depends_on:
      - db
    environment:
      HOME: /var/www/html
      APP_ENV: develop
    volumes:
      - "./assets:/var/www/html/assets"
      - "./config:/var/www/html/config"
      - "./data:/var/www/html/data"
      - "./migrations:/var/www/html/migrations"
      - "./src:/var/www/html/src"
      - "./templates:/var/www/html/templates"
      - "./tests:/var/www/html/tests"
      - "./translations:/var/www/html/translations"
    ports:
      - "8080:80"

  db:
    container_name: ricardo-db
    image: mariadb:10.6.11
    restart: on-failure
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    environment:
      - MYSQL_ROOT_PASSWORD=Qy8ojBPmiF6Tfezt
      - MYSQL_DATABASE=technical_test
      - MYSQL_USER=technical_test
      - MYSQL_PASSWORD=Qy8ojBPmiF6Tfezt
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db:
